github.com:
    users:
        dorrelredmond: {oauth_token: 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}
    git_protocol: https
    user: dorrelredmond
    oauth_token: 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
