#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


# Themes
exec-once = swww-daemon

# Widgets
exec-once = waybar

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Hypr Services
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprsunset

# Audio
exec-once = pipewire & pipewire-puls & wireplumber

# Misc Apps
exec-once = swaync
exec-once = dropbox
