#############
### STYLE ###
#############

source=../theme/mocha.conf # Catppuccin Theme Colors

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 1

    col.active_border = $pink
    col.inactive_border = $surface0

    allow_tearing = false # Allows 'immediate' window rule to work

    layout = dwindle
}

dwindle {
    preserve_split = true # You probably want this
    smart_split = false
    smart_resizing = true
}

decoration {
    rounding = 15

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = $overlay0
    }

    blur {
        enabled = true
        vibrancy = 0.8
        contrast = 0.6
        size = 8
        passes = 2
        ignore_opacity = true
        new_optimizations = true
    }
}
